version: '3.8'

services:
  web_tracerstudy:
    build: .
    container_name: web_tracerstudy
    restart: always
    ports:
      - "9004:80"
    volumes:
      - .:/var/www/html
    networks:
      - default
      - mss_network

networks:
  mss_network:
    external: true
    name: mss-server-panel_mss-network
